"""Paper export strategies — LaTeX table, CSV, plot script, caption.

Architecture: AS-5 (2) "論文用エクスポート機能" in
``docs/architecture/02_architecture_significance.md``: the comparison
result must convert into paper-ready artifacts in < 3 steps (QA-6).
Each artifact kind is a Strategy (:class:`PaperArtifactRenderer`); the
:class:`PaperExporter` composes a tuple of strategies and writes their
output next to each other so the LaTeX table, the data and the plot
script stay in sync.

All renderers are pure (``ComparisonTable`` in, ``str`` out); only
:meth:`PaperExporter.export` touches the filesystem.
"""

from __future__ import annotations

import csv
import io
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

from gridflow.domain.result.comparison_table import ComparisonTable

_LATEX_SPECIALS = (
    ("\\", r"\textbackslash{}"),
    ("&", r"\&"),
    ("%", r"\%"),
    ("$", r"\$"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
)


def latex_escape(text: str) -> str:
    for raw, escaped in _LATEX_SPECIALS:
        text = text.replace(raw, escaped)
    return text


class PaperArtifactRenderer(Protocol):
    """Strategy: render one paper artifact from a comparison table."""

    @property
    def filename(self) -> str:
        """Output filename relative to the export directory."""
        ...

    def render(self, table: ComparisonTable) -> str:
        """Return the full artifact content."""
        ...


class LatexTableRenderer:
    """booktabs comparison table; best value per metric in bold."""

    filename = "table.tex"

    def render(self, table: ComparisonTable) -> str:
        n_metrics = len(table.metrics)
        best = tuple(table.best_method(i) for i in range(n_metrics))
        header_cells = ["Method"]
        for spec in table.metrics:
            label = latex_escape(spec.name)
            if spec.unit:
                label += f" [{latex_escape(spec.unit)}]"
            header_cells.append(label)
        lines = [
            "% Auto-generated by `gridflow export paper` - do not edit by hand.",
            "\\begin{table}[t]",
            "  \\centering",
            f"  \\caption{{{latex_escape(table.title)}}}",
            "  \\label{tab:comparison}",
            f"  \\begin{{tabular}}{{l{'r' * n_metrics}}}",
            "    \\toprule",
            "    " + " & ".join(header_cells) + " \\\\",
            "    \\midrule",
        ]
        for row in table.rows:
            method_cell = latex_escape(row.method)
            if row.method == table.highlight:
                method_cell = f"\\textbf{{{method_cell}}}"
            cells = [method_cell]
            for i, value in enumerate(row.values):
                mean_text = f"{value.mean:.2f}"
                if row.method == best[i]:
                    mean_text = f"\\textbf{{{mean_text}}}"
                if value.has_ci:
                    mean_text += f" [{value.ci_low:.2f}, {value.ci_high:.2f}]"
                cells.append(mean_text)
            lines.append("    " + " & ".join(cells) + " \\\\")
        lines += [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
        ]
        return "\n".join(lines) + "\n"


class CsvDataRenderer:
    """Flat CSV: one row per method, mean/ci columns per metric."""

    filename = "data.csv"

    def render(self, table: ComparisonTable) -> str:
        fieldnames = ["method", "n"]
        for spec in table.metrics:
            fieldnames += [
                f"{spec.name}_mean",
                f"{spec.name}_ci_low",
                f"{spec.name}_ci_high",
            ]
        buf = io.StringIO()
        writer = csv.DictWriter(buf, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        for row in table.rows:
            record: dict[str, object] = {"method": row.method, "n": row.n}
            for spec, value in zip(table.metrics, row.values, strict=True):
                record[f"{spec.name}_mean"] = value.mean
                record[f"{spec.name}_ci_low"] = "" if value.ci_low is None else value.ci_low
                record[f"{spec.name}_ci_high"] = "" if value.ci_high is None else value.ci_high
            writer.writerow(record)
        return buf.getvalue()


class MatplotlibScriptRenderer:
    """Standalone matplotlib script reading the sibling ``data.csv``."""

    filename = "plot_comparison.py"

    def render(self, table: ComparisonTable) -> str:
        metric_names = [spec.name for spec in table.metrics]
        metric_units = [spec.unit for spec in table.metrics]
        return f'''"""Comparison bar chart for: {table.title}

Auto-generated by `gridflow export paper` - reads the sibling data.csv.
Usage: python plot_comparison.py [output.png]
"""

import csv
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

METRICS = {metric_names!r}
UNITS = {metric_units!r}
HIGHLIGHT = {table.highlight!r}

here = Path(__file__).resolve().parent
with (here / "data.csv").open() as f:
    rows = list(csv.DictReader(f))

fig, axes = plt.subplots(1, len(METRICS), figsize=(4.0 * len(METRICS), 3.2))
if len(METRICS) == 1:
    axes = [axes]
for ax, metric, unit in zip(axes, METRICS, UNITS):
    methods = [r["method"] for r in rows]
    means = [float(r[metric + "_mean"]) for r in rows]
    err_low, err_high = [], []
    for r, m in zip(rows, means):
        lo, hi = r[metric + "_ci_low"], r[metric + "_ci_high"]
        err_low.append(m - float(lo) if lo else 0.0)
        err_high.append(float(hi) - m if hi else 0.0)
    colors = ["#d62728" if m == HIGHLIGHT else "#7f7f7f" for m in methods]
    ax.bar(methods, means, yerr=[err_low, err_high], capsize=4, color=colors)
    ax.set_ylabel(metric + (f" [{{unit}}]" if unit else ""))
    ax.tick_params(axis="x", rotation=30)
fig.suptitle({table.title!r})
fig.tight_layout()
out = sys.argv[1] if len(sys.argv) > 1 else str(here / "comparison.png")
fig.savefig(out, dpi=200)
print(f"wrote {{out}}")
'''


class CaptionRenderer:
    """Caption template auto-describing the experiment conditions."""

    filename = "caption.txt"

    def render(self, table: ComparisonTable) -> str:
        methods = ", ".join(row.method for row in table.rows)
        lines = [
            f"{table.title}. Comparison of {len(table.rows)} methods "
            f"({methods}).",
            "Error bounds are 95% confidence intervals; "
            "the best value per metric is shown in bold.",
        ]
        if table.highlight:
            lines.append(f"{table.highlight} is the proposed method.")
        if table.conditions:
            lines.append("Experiment conditions: " + "; ".join(f"{k}: {v}" for k, v in table.conditions) + ".")
        return "\n".join(lines) + "\n"


def default_renderers() -> tuple[PaperArtifactRenderer, ...]:
    return (
        LatexTableRenderer(),
        CsvDataRenderer(),
        MatplotlibScriptRenderer(),
        CaptionRenderer(),
    )


@dataclass(frozen=True)
class PaperExporter:
    """Compose rendering strategies and write their artifacts to a directory."""

    renderers: tuple[PaperArtifactRenderer, ...] = field(default_factory=default_renderers)

    def export(self, table: ComparisonTable, out_dir: Path) -> tuple[Path, ...]:
        out_dir.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []
        for renderer in self.renderers:
            path = out_dir / renderer.filename
            path.write_text(renderer.render(table), encoding="utf-8")
            written.append(path)
        return tuple(written)
